### ISSUE TITLE
client is skidded

### ISSUE THREAD

**Issue by Errorcrafter** [Matejko06/MatHax-Client-Legacy#1]
# Description of the error
this entire client is just a meteor paste and the retarded 10yo owner goes around advertising it in DMs and fucking asked addon devs to make their addons compatible with this pile of hot garbage

# Expected behaviour
client is not skidded

**Comment by WhoAmI2704** [comment]
if u dont like the client then just dont use it fucking 5yo fag
the website obviously says its a meteor fork

**Comment by Errorcrafter** [comment]
ah yes meteor fork it definitely adds new features and doesnt skid from the bedtrap leak and 30 other public addons

sure do love it when my defo not skidded meteor fork works [perfectly fine and exactly as intended](https://media.discordapp.net/attachments/875153727013650486/886323776671850546/2021-09-11_16.23.12.png?width=1191&height=670)!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Matejko06** [comment]
*10yo owner goes around advertising it in DMs and fucking asked addon devs to make their addons compatible with this pile of hot garbage*

CarlosVite is not the owner of this client.
